// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "BSV Blockchain",
            "url": "https://github.com/bsv-blockchain/arcade"
        },
        "license": {
            "name": "Open BSV License",
            "url": "https://github.com/bsv-blockchain/arcade/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/events/{callbackToken}": {
            "get": {
                "description": "Subscribe to transaction status updates via Server-Sent Events",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Transaction status stream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Callback token from transaction submission",
                        "name": "callbackToken",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Resume from event ID",
                        "name": "Last-Event-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/header/hash/{hash}": {
            "get": {
                "description": "Get a block header with the specified hash",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chain"
                ],
                "summary": "Get header by hash",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Block hash (hex)",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/chaintracks.BlockHeader"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cmd_arcade.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/cmd_arcade.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/header/height/{height}": {
            "get": {
                "description": "Get a block header at the specified height",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chain"
                ],
                "summary": "Get header by height",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Block height",
                        "name": "height",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/chaintracks.BlockHeader"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cmd_arcade.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/cmd_arcade.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/headers": {
            "get": {
                "description": "Get multiple consecutive block headers as concatenated raw hex",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chain"
                ],
                "summary": "Get multiple headers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Starting height",
                        "name": "height",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of headers",
                        "name": "count",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_arcade.HeadersResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cmd_arcade.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check server health and database connectivity",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Info"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    }
                }
            }
        },
        "/height": {
            "get": {
                "description": "Get the current blockchain height",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chain"
                ],
                "summary": "Get height",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_arcade.HeightResponse"
                        }
                    }
                }
            }
        },
        "/network": {
            "get": {
                "description": "Get the BSV network name (main, test, etc.)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chain"
                ],
                "summary": "Get network",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_arcade.NetworkResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/cmd_arcade.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/policy": {
            "get": {
                "description": "Get transaction validation policy and fee requirements",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Info"
                ],
                "summary": "Get policy",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.PolicyResponse"
                        }
                    }
                }
            }
        },
        "/tip": {
            "get": {
                "description": "Get the current chain tip block header",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chain"
                ],
                "summary": "Get chain tip",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/chaintracks.BlockHeader"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/cmd_arcade.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tip/stream": {
            "get": {
                "description": "Subscribe to chain tip updates via Server-Sent Events",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "Chain"
                ],
                "summary": "Chain tip stream",
                "responses": {
                    "200": {
                        "description": "SSE stream",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tx": {
            "post": {
                "description": "Submit a raw transaction for broadcast to the network",
                "consumes": [
                    "application/json",
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Submit transaction",
                "parameters": [
                    {
                        "description": "Transaction request",
                        "name": "transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.TransactionRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Webhook callback URL",
                        "name": "X-CallbackUrl",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Callback token for SSE/webhook auth",
                        "name": "X-CallbackToken",
                        "in": "header"
                    },
                    {
                        "type": "boolean",
                        "description": "Receive all status updates",
                        "name": "X-FullStatusUpdates",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cmd_arcade.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/cmd_arcade.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tx/{txid}": {
            "get": {
                "description": "Get the current status of a submitted transaction",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get transaction status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "txid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TransactionResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/cmd_arcade.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/cmd_arcade.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/txs": {
            "post": {
                "description": "Submit multiple raw transactions for broadcast",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Submit multiple transactions",
                "parameters": [
                    {
                        "description": "Array of transactions",
                        "name": "transactions",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.TransactionRequest"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.TransactionResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cmd_arcade.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.FeeAmount": {
            "type": "object",
            "properties": {
                "bytes": {
                    "type": "integer"
                },
                "satoshis": {
                    "type": "integer"
                }
            }
        },
        "api.HealthResponse": {
            "type": "object",
            "properties": {
                "healthy": {
                    "type": "boolean"
                },
                "reason": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "api.PolicyResponse": {
            "type": "object",
            "properties": {
                "maxscriptsizepolicy": {
                    "type": "integer"
                },
                "maxtxsigopscountspolicy": {
                    "type": "integer"
                },
                "maxtxsizepolicy": {
                    "type": "integer"
                },
                "miningFee": {
                    "$ref": "#/definitions/api.FeeAmount"
                }
            }
        },
        "api.TransactionRequest": {
            "type": "object",
            "properties": {
                "rawTx": {
                    "type": "string"
                }
            }
        },
        "api.TransactionResponse": {
            "type": "object",
            "properties": {
                "blockHash": {
                    "type": "string"
                },
                "blockHeight": {
                    "type": "integer"
                },
                "competingTxs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "extraInfo": {
                    "type": "string"
                },
                "merklePath": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "txStatus": {
                    "type": "string"
                },
                "txid": {
                    "type": "string"
                }
            }
        },
        "chaintracks.BlockHeader": {
            "type": "object",
            "properties": {
                "bits": {
                    "description": "4 bytes - Difficulty target",
                    "type": "integer"
                },
                "hash": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "height": {
                    "description": "Block height in the chain",
                    "type": "integer"
                },
                "merkleRoot": {
                    "description": "32 bytes - Merkle root hash",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "nonce": {
                    "description": "4 bytes - Nonce",
                    "type": "integer"
                },
                "previousHash": {
                    "description": "32 bytes - Previous block hash",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "time": {
                    "description": "4 bytes - Block timestamp (Unix time)",
                    "type": "integer"
                },
                "version": {
                    "description": "4 bytes - Block version",
                    "type": "integer"
                }
            }
        },
        "cmd_arcade.ErrorResponse": {
            "description": "Error response",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid request"
                }
            }
        },
        "cmd_arcade.HeadersResponse": {
            "description": "Concatenated raw headers in hex",
            "type": "object",
            "properties": {
                "headers": {
                    "type": "string",
                    "example": "0100000000000000..."
                }
            }
        },
        "cmd_arcade.HeightResponse": {
            "description": "Current blockchain height",
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer",
                    "example": 873421
                }
            }
        },
        "cmd_arcade.NetworkResponse": {
            "description": "Network name response",
            "type": "object",
            "properties": {
                "network": {
                    "type": "string",
                    "example": "main"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Bearer token authentication",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Arcade API",
	Description:      "BSV transaction broadcast service with ARC-compatible endpoints and blockchain header queries.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
